trailingComma: "es5"
tabWidth: 4
printWidth: 80
plugins:
    [
        "prettier-plugin-sql",
        "prettier-plugin-embed",
        "prettier-plugin-prisma",
        "prettier-plugin-astro",
        "prettier-plugin-sh",
    ]

# prettier-plugin-sql config
language: postgresql
keywordCase: upper

# prettier-plugin-embed config
embeddedSqlTags: ["sql", "prisma.$queryRaw", "prisma.$queryRawUnsafe"]
