services:
    db:
        image: postgres:17.2
        container_name: ${DB_HOSTNAME}
        hostname: ${DB_HOSTNAME}
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - ${DB_PORT}:5432
        volumes:
            - psql_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
            interval: 10s
            retries: 3
            timeout: 5s
            start_period: 10s
        networks:
            - app-network

    backend:
        container_name: backend
        stdin_open: true
        build:
            context: back/
            dockerfile: back.dockerfile
        environment:
            - DATABASE_URL
            - API_PORT
            - API_DOMAIN
            - API_URL
            - FRONT_DOMAIN
            - FRONT_URL
        ports:
            - ${API_PORT}:${API_PORT}
            - ${PRISMA_PORT}:5555
        depends_on:
            - db
        volumes:
            - type: bind
              source: ./back
              target: /back

            - /back/node_modules
        networks:
            - app-network

    frontend:
        container_name: frontend
        stdin_open: true
        build:
            context: front/
            dockerfile: front.dockerfile
        environment:
            - API_URL
            - API_DOMAIN
            - FRONT_DOMAIN
            - FRONT_URL
        ports:
            - 80:4321
        volumes:
            - ./front:/front
            - /front/node_modules
        networks:
            - app-network
volumes:
    psql_data:
networks:
    app-network:
        driver: bridge
