services:
    db:
        image: postgres:17.2
        container_name: ${DB_HOSTNAME}
        hostname: ${DB_HOSTNAME}
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - 5432:5432
        volumes:
            - ./psql_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
            interval: 10s
            retries: 3
            timeout: 5s
            start_period: 10s
        networks:
            - app-network

    backend:
        container_name: backend
        build:
            dockerfile: back/back.dockerfile
        environment:
            - DATABASE_URL
            - EXPRESS_PORT
        ports:
            - 3000:3000
            - 5555:5555
        depends_on:
            - db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
