openapi: "3.0.0"
info:
    title: bb-tcg-api
    version: "1.0.0"
servers:
  - url: /api/v1
paths: {}
components:
    securitySchemes:
        CookieAuth:
            type: apiKey
            in: cookie
            name: token
    schemas:
        Password:
            description: "The password used for authenticating the user."
            type: "string"
            format: "password"
        StringIdentifier:
            type: string
            description: "A unique alphanumerical lowercase string that functions as a key."
            pattern: "^[a-z0-9_]+$"
        User:
            type: object
            properties:
                id:
                    type: integer
                username:
                    $ref: "#/components/schemas/StringIdentifier"
                profileName:
                    type: string
                    nullable: true
                profilePictureUrl:
                    type: string
                createdAt:
                    type: string
                    format: date-time
                    nullable: true
        Error:
            type: object
            required: [message]
            properties:
                path:
                    type: string
                errorCode:
                    type: string
                message:
                    type: string
                location:
                    type: string
    responses:
        BadRequest:
            description: The request was invalid.
            content:
                application/json:
                    schema:
                        type: object
                        required: [errors]
                        properties:
                            errors:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Error"
        InternalServerError:
            description: "An internal server error occurred."
