services:

  db:
    image: postgres:17.2

    build:
      dockerfile: docker/db.dockerfile

    env_file:
      - path: db.env

    container_name: db
    environment:
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_USER: dbuser
      POSTGRES_DB: brakingbadDB
    ports:
      - 5432:5432
    volumes:
      - ./psql_data:/var/lib/postgresql/data

  web:
    image: node:23-alpine3.20 

    build:
      dockerfile: docker/back.dockerfile
      
    container_name: back

    ports:
      - 3000:3000


