services:
  db:
    build: 
      docker/db.dockerfile
    env_file:
      - path: docker/db.env
    ports:
      - 3306:3306

    healthcheck:
      test: ["CMD", "", "--inno"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  phpmyadmin:
    image:  phpmyadmin/phpadmin.env
    env_file:
      - path: docker/phpadmin.env
    ports:
      - 3307:80
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      dockerfile: docker/web.dockerfile
    env_file:
      - path: doker/web.env
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
  



