services:

  db:
    image: postgres:17.2
    container_name: database
    environment:
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_USER: dbuser
      POSTGRES_DB: brakingbadDB
    ports:
      - 5432:5432
    volumes:
      - ./psql_data:/var/lib/postgresql/data

  web:
    build:
      dockerfile: docker/web.dockerfile
    env_file:
      - path: doker/web.env
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
  



